# Generated by Django 5.2.1 on 2025-06-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('birthdate', models.DateField()),
                ('my_email_password', models.CharField(max_length=45)),
            ],
        ),
    ]
